### ISSUE TITLE
Authorization

### ISSUE THREAD

**Issue by Thecentury** [praeclarum/Ooui#102]
Hi!

How do I can perform authorization in Ooui?
I would like web app to be available only for authorized users.

**Comment by praeclarum** [comment]
I would stick to cookie auth using ASP.NET identity. Then it's up to you to present the UI and such for it.

Otherwise, you will have to implement your own. This can be as simple as a global user object that has a flag - logged in or not.

Sorry but auth is out of the scope for this project and I am leaving auth to other libraries. Perhaps this can change in the future if there is huge demand.
