### ISSUE TITLE
Question: Why WASM?

### ISSUE THREAD

**Issue by Mike-EEE** [praeclarum/Ooui#90]
So I have to admit I am a little confused on the support for WASM here.  From what I understand, Ooui uses HTML5/CSS for all of its rendering.  This is default supported behavior by every modern browser, so it would seem supporting WASM would not be necessary, which leads me to my question on why you would want to incur the overhead to support something that seems unnecessary.  Clearly I must be missing (and/or misunderstanding) something here. 😆

**Comment by praeclarum** [comment]
Ooui is indeed an HTML5/CSS library but has a certain burden on the server (maintaining web socket connections and such) and does not support the disconnected scenario.

With web assembly, you gain the ability to run offline with no server cost (you can host your app on a static web server). This also enables Xamarin.Forms to run entirely in browser making it act more like its mobile counterparts.

The wasm support required only minor changes to the codebase to support and is a huge win given the investment (50 lines were added ooui.js and two new functions were added to the UI class).

This is not a change in the direction of Ooui - I plan on supporting both of these scenarios (dumb client/smart client) in order to let users decide which one is the best for their apps.

**Comment by Terricide** [comment]
I'm pretty excited for this. I've been following the blazor project and it looks just as exciting. 

Though I had a question with xaramin.forms support is it a subset or does it support every control?

**Comment by praeclarum** [comment]
@Terricide every control will eventually be supported though there are currently a few left that need implementing. But no, this is not a subset. There are a couple work items to start tracking the work left (#85 and #87)

**Comment by Mike-EEE** [comment]
Awesome... thank you for the insight and explanation, @praeclarum!  And much respect/admiration for all your work here.  Very genius and inspiring. 👍

In my view, this approach and strategy is the answer [to a much requested ubiquitous .NET](https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/10027638-create-a-ubiquitous-net-client-application-develo).
